### ISSUE TITLE
Is there a way to specify folder in "interactive" mode?

### ISSUE THREAD

**Issue by moshfeu** [galElmalah/scaffolder#15]
Similar to `create -f`

**Comment by galElmalah** [comment]
Thanks for opening an issue Moshe :) 
nope, but you can nest your files under a specific folder like this [example](https://github.com/galElmalah/scaffolder-templates-example/tree/master/scaffolder/typescript-module/%7B%7BmoduleName%7D%7D) 
does it make sense for your use case?

**Comment by moshfeu** [comment]
If I'm not mistaking, it requires to have a different repository for the templates, right?

**Comment by galElmalah** [comment]
No, you can create nested structures in your computer as well 😄 
something like that
<img width="383" alt="Screen Shot 2020-08-31 at 21 27 46" src="https://user-images.githubusercontent.com/40733145/91753701-f2f3a480-ebd0-11ea-8f37-c35752b737cb.png">

from the react-index template, you will get a folder with the component name and an index file inside with the defined template.
you can separate the keys as well and just add something like {{folderName}} as the folder name, and even add a custom question to make the cli prompt you with something like "what's the name of the folder you want your component in?"
instead of the default "Enter a value for the following parameter "folderName""

**Comment by moshfeu** [comment]
working like a charm :)

**Comment by galElmalah** [comment]
> working like a charm :)

Til 🚀
